language: ruby
rvm:
  - 2.3
cache:
  - bundler
gemfile: travisGemfile
install:
  - bundle install
before_script:
  - chmod +x install.sh
script: "./install.sh"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
    - master
