# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]

paginate: 7
paginate_path: "/page/:num/"
comments: true

source: .
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: ZK - Software Craftsman
description: "My personal blog in the world of one and zero!"
keywords: "Zac, Kwan, software, developer, CI, CD, blog, web, craftsman, python, swift, docker, django"
url: https://zaccc123.github.io
baseurl: ""


google_analytics: UA-86547907-2
repo: https://github.com/zaccc123.github.io
disqus_shortname: "zac_kwan"
disqus_site_shortname: "zaccc123"

# Author settings
author:
  name: Zac Kwan
  job: Maker 👨‍💻, Full Stack Dev, Tech Lead
  desc: "I have worked as a mobile engineer(iOS), backend Engineer (python) and now as a Technical Lead. I enjoy building my own product at night and whenever I am free."
  bio: "I like to ensure that all my project is set up with continuous integration. Therefore, I make <a href='http://flymusca.com'>Musca - a mac taskbar app</a>  that keeps track of you Github Commit statuses."
  thumb: /images/author.jpg
  email: zac.kwan.wh@gmail.com
  url: https://zaccc123.github.io/
  github: https://github.com/Zaccc123
  linkedin: https://www.linkedin.com/in/zackwan
  twitter: https://twitter.com/Zaccc123/
  medium: https://medium.com/@Zaccc123
  stackoverflow: http://stackoverflow.com/users/6539131/zac-kwan
# navbar pages
navbar:
  - slug: about
    title: About
  # Can define new sub nav bar here
  # - slug: blog
  #   title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
