# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/page/:num/"
comments: true

source: .
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: ZK - Software Craftsman
description: "My personal blog in the world of one and zero!"
keywords: "Zac, Kwan, software, developer, SEO, blog, web, craftsman, python, swift, docker, django"
url: https://zaccc123.github.io
baseurl: ""


google_analytics: UA-86547907-2
repo: https://github.com/zaccc123.github.io
disqus_shortname: "zac_kwan"
disqus_site_shortname: "zaccc123"

# Author settings
author:
  name: Zac Kwan
  job: Software Craftsman
  desc: "I have worked as a mobile engineer(iOS), backend Engineer (python) and now a Technical Lead. I enjoy solving difficult problem with an elegant solution. Feel free to ping me for an intellectual conversation or a short coffee chat!"
  bio: "A good craftsman possesses a good set of tools. I am always honing my skills to create a good set of development flow to build a better product."
  thumb: /images/author.jpg
  email: zac.kwan.wh@gmail.com
  url: https://zaccc123.github.io/
  github: https://github.com/Zaccc123
  linkedin: https://www.linkedin.com/in/zackwan
  stackoverflow: http://stackoverflow.com/users/6539131/zac-kwan
# navbar pages
navbar:
  - slug: about
    title: About
  # Can define new sub nav bar here
  # - slug: blog
  #   title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
